const axios = require("axios");

const CANDIDATE_MODELS = [
  process.env.GEMINI_MODEL || "gemini-2.5-flash",
  "gemini-2.5-pro",
  "gemini-3.5-flash-lite",
  "gemini-3.5-flash",
];

const PROMPT = `You are an expert programming contest and technical interview curriculum scanner.
Analyze this document, image, or syllabus sheet and extract ALL coding, DSA, and programming problems.

CRITICAL INSTRUCTIONS FOR PROBLEM TITLES AND LINKS:
1. "number": The problem number or serial index if present (e.g. "1", "4A", "142"), or null.
2. "title": Extract the clean, core problem title. ALWAYS STRIP:
   - Prefixes like "Q1.", "Question 1:", "Problem 1 -", "Day 4:", "#101", "LC 56.", etc.
   - Suffixes like "(Easy)", "[Medium]", "(Hard)", "- LeetCode", "[Arrays]", etc.
   Example: "Q1. Two Sum (Easy)" -> "Two Sum"
   Example: "Day 3 - Merge Intervals [LC 56]" -> "Merge Intervals"
3. "platform": "LeetCode", "Codeforces", "CodeChef", "GeeksforGeeks", "HackerRank", "takeUforward", or null.
4. "questionUrl": The practice problem URL where the student solves the question (e.g. leetcode.com/problems/..., geeksforgeeks.org/..., codeforces.com/..., takeuforward.org/...). If a link points to an online judge or practice question, put it here.
5. "solutionUrl": The instructor's solution, video, editorial, or notes URL (e.g. Google Drive, YouTube, GitHub, Notion, Loom, or personal blog created by the instructor). If a link points to an answer, code, video, or drive, put it here.
6. "url": If only one URL is provided and you cannot determine whether it is question or solution, put it in "url".
7. "difficulty": "Easy", "Medium", "Hard", or null.
8. "topic": The standard interview pattern module (e.g. "Math & Fundamentals", "Arrays & Hashing", "Two Pointers & Sliding Window", "Prefix Sum", "Binary Search", "Strings", "Linked Lists", "Stack & Queue", "Trees & BST", "Graphs", "Dynamic Programming", "Heaps & Greedy", or "Bit Manipulation"), or null.

Return ONLY a valid JSON array of objects with the exact keys:
[
  {
    "number": "1",
    "title": "Two Sum",
    "platform": "LeetCode",
    "questionUrl": "https://leetcode.com/problems/two-sum/",
    "solutionUrl": "https://drive.google.com/file/d/...",
    "url": null,
    "difficulty": "Easy",
    "topic": "Arrays"
  }
]`;

const MIME_MAP = {
  pdf: "application/pdf",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
};

/**
 * Scan a document or raw text using Google Gemini API
 */
exports.scanSheetWithGemini = async ({
  fileBase64,
  mimeType = "application/pdf",
  fileName = "",
  rawText = "",
  apiKey = null,
}) => {
  const activeKey = apiKey || process.env.GEMINI_API_KEY;

  if (!activeKey || activeKey === "your_gemini_api_key_here") {
    throw new Error(
      "GEMINI_API_KEY is not configured. Please set GEMINI_API_KEY in server/.env or provide your Google Gemini API key."
    );
  }

  const parts = [{ text: PROMPT }];

  if (rawText?.trim()) {
    parts.push({ text: `Document Content:\n${rawText.trim()}` });
  }

  if (fileBase64) {
    const cleanBase64 = fileBase64.includes(",") ? fileBase64.split(",")[1] : fileBase64;
    const ext = (fileName.split(".").pop() || "").toLowerCase();
    const isText = /text|csv|json|md|txt/.test(`${mimeType} ${ext}`);

    if (isText) {
      try {
        const decoded = Buffer.from(cleanBase64, "base64").toString("utf8");
        parts.push({ text: `Document Content (${fileName || "uploaded file"}):\n${decoded}` });
      } catch {
        parts.push({ inline_data: { mime_type: "text/plain", data: cleanBase64 } });
      }
    } else {
      const finalMime = MIME_MAP[ext] || mimeType || "application/pdf";
      parts.push({ inline_data: { mime_type: finalMime, data: cleanBase64 } });
    }
  }

  const payload = {
    contents: [{ parts }],
    generationConfig: {
      temperature: 0.2,
      response_mime_type: "application/json",
    },
  };

  let lastError = null;

  for (const model of CANDIDATE_MODELS) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${activeKey}`;
      const response = await axios.post(url, payload, {
        headers: { "Content-Type": "application/json" },
        timeout: 60000,
      });

      const textOutput = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!textOutput) throw new Error("No output generated by Gemini");

      const parsed = JSON.parse(textOutput);
      const items = Array.isArray(parsed) ? parsed : (parsed?.problems || parsed?.items || []);

      return items.map((item) => ({
        number: item.number ? String(item.number).trim() : null,
        title: item.title ? String(item.title).trim() : "Untitled Problem",
        platform: item.platform ? String(item.platform).trim() : null,
        questionUrl: item.questionUrl && String(item.questionUrl).startsWith("http") ? String(item.questionUrl).trim() : null,
        solutionUrl: item.solutionUrl && String(item.solutionUrl).startsWith("http") ? String(item.solutionUrl).trim() : null,
        url: item.url && String(item.url).startsWith("http") ? String(item.url).trim() : null,
        difficulty: item.difficulty || null,
        topic: item.topic || null,
      }));
    } catch (err) {
      lastError = err;
      if (err.response?.status === 404) continue;
      if (err.response?.status === 400 || err.response?.status === 403) {
        throw new Error(err.response?.data?.error?.message || "Invalid Gemini API key or request error");
      }
    }
  }

  throw new Error(
    lastError?.response?.data?.error?.message ||
    lastError?.message ||
    "Failed to scan document with Google Gemini API."
  );
};

/**
 * Intelligently classify a list of problems into structured curriculum modules using Gemini 3.5
 */
exports.categorizeProblemsWithGemini = async (problems = [], apiKey = null) => {
  if (!Array.isArray(problems) || problems.length === 0) return problems;

  const activeKey = apiKey || process.env.GEMINI_API_KEY;
  if (!activeKey || activeKey === "your_gemini_api_key_here") {
    return problems.map((p) => ({
      ...p,
      module: inferProblemCategory(p.title, p.module || p.topic),
      topic: inferProblemCategory(p.title, p.module || p.topic),
    }));
  }

  const needCategorization = [];
  const result = problems.map((p, idx) => {
    const rawMod = String(p.module || p.topic || "").trim();
    const isGeneric =
      !rawMod ||
      [
        "dsa",
        "core dsa",
        "custom sheet",
        "dsa patterns",
        "general",
        "official problems",
        "custom-1",
        "custom problem",
        "problems",
      ].includes(rawMod.toLowerCase());

    if (isGeneric) {
      needCategorization.push({ originalIndex: idx, id: p.id || idx + 1, title: p.title });
    }
    return { ...p, module: rawMod || "Arrays & Hashing", topic: rawMod || "Arrays & Hashing" };
  });

  if (needCategorization.length === 0) {
    return result;
  }

  const BATCH_SIZE = 50;
  for (let i = 0; i < needCategorization.length; i += BATCH_SIZE) {
    const batch = needCategorization.slice(i, i + BATCH_SIZE);
    const promptText = `You are an expert DSA curriculum architect (like Striver, NeetCode, or LeetCode Explore).
Organize the following coding interview problems into standardized, pedagogical topic modules based on their problem titles and algorithmic patterns.
Standard modules include:
- "Arrays & Hashing"
- "Two Pointers & Sliding Window"
- "Prefix Sum"
- "Binary Search"
- "Strings & Pattern Matching"
- "Linked Lists"
- "Stack & Queue"
- "Trees & BST"
- "Graphs & Disjoint Set"
- "Dynamic Programming"
- "Heaps & Greedy"
- "Bit Manipulation"
- "Math & Number Theory"
- "Backtracking & Recursion"

Input problems:
${JSON.stringify(batch.map((b) => ({ id: b.id, title: b.title })))}

Return ONLY a valid JSON array of objects with the exact schema:
[
  { "id": <same id>, "module": "<Module Name>" }
]`;

    const payload = {
      contents: [{ parts: [{ text: promptText }] }],
      generationConfig: {
        temperature: 0.1,
        response_mime_type: "application/json",
      },
    };

    const classifiedMap = new Map();
    for (const model of CANDIDATE_MODELS) {
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${activeKey}`;
        const response = await axios.post(url, payload, {
          headers: { "Content-Type": "application/json" },
          timeout: 45000,
        });

        const textOutput = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (textOutput) {
          const parsed = JSON.parse(textOutput);
          const items = Array.isArray(parsed) ? parsed : parsed?.items || parsed?.problems || [];
          items.forEach((item) => {
            if (item.id != null && item.module) {
              classifiedMap.set(String(item.id), String(item.module).trim());
            }
          });
          break;
        }
      } catch (err) {
        continue;
      }
    }

    batch.forEach((b) => {
      const assigned = classifiedMap.get(String(b.id)) || inferProblemCategory(b.title);
      result[b.originalIndex].module = assigned;
      result[b.originalIndex].topic = assigned;
    });
  }

  return result;
};
